language: node_js
node_js:
  - lts/*

cache:
  npm: false
  directories:
    - ./.yarn/cache

# required for yarn version check on branches
git:
  depth: false

branches:
  only:
    - master
    - develop

install: yarn
script:
  - yarn ci
  - yarn build:fresh
  - yarn version check

deploy:
  provider: script
  skip_cleanup: true
  script: bash bin/release.sh
  on:
    branch: master
