language: node_js
node_js:
  - lts/*

cache:
  npm: false
  directories:
    - ./.yarn/cache

# required for yarn version check on branches
git:
  depth: false

# only build on master & develop branches
# PRs will also be built if enabled and targetting either of these branches
# tags will not be built
branches:
  only:
    - master
    - develop

install: yarn
script:
  - yarn ci
  - yarn build:fresh
  - yarn version check
after_success: '[[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] && bash bin/tag.sh'
deploy:
  provider: script
  skip_cleanup: true
  script: yarn publish
  on:
    branch: master
    tags: true
