language: node_js
node_js:
  - lts/*
# ref: https://gist.github.com/dennisreimann/c2a6ef58544861f7e13762e06e146dac
cache:
  npm: false
  directories:
    - ./.yarn/cache

branches:
  only:
    - master
    - develop

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v

install: yarn
script:
  - yarn ci
  - yarn
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    branch: master
